apiVersion: v1
kind: ConfigMap
metadata:
  name: cine-config
  namespace: cine
data:
  # Ruta interna dentro del contenedor
  MOVIES_FOLDER: "/data/movies"

  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "5000"

  # Estas rutas internas no cambian
  UPLOAD_FOLDER: "/app/uploads"
  TEMP_FOLDER: "/app/temp"
  OUTPUT_FOLDER: "/app/outputs"
  LOG_FOLDER: "/app/logs"
