apiVersion: v1
kind: ConfigMap
metadata:
  name: cine-config
  namespace: cine
data:
  POCKETBASE_URL: "http://pocketbase.cine.svc.cluster.local:8070"
  MOVIES_FOLDER: "/media/d/audiovisual"
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "5000"
  UPLOAD_FOLDER: "./uploads"
  TEMP_FOLDER: "./temp"
  OUTPUT_FOLDER: "./outputs"
