apiVersion: apps/v1
kind: Deployment
metadata:
  name: cine-platform
  namespace: cine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cine-platform
  template:
    metadata:
      labels:
        app: cine-platform
    spec:
      containers:
        - name: cine-platform
          image: felixmurcia/cine-platform:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
