apiVersion: v1
kind: Service
metadata:
  name: cine-platform-service
  namespace: cine
spec:
  type: NodePort
  selector:
    app: cine-platform
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
